{{- if and (not .Values.existingSecret) .Values.dsn -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyjobkit.fullname" . }}-dsn
  labels: {{- include "pyjobkit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.dsnKey }}: {{ .Values.dsn | quote }}
{{- end -}}
{{- if and (not .Values.webhookSecretExistingSecret) .Values.webhookSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyjobkit.fullname" . }}-webhook
  labels: {{- include "pyjobkit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhookSecretKey }}: {{ .Values.webhookSecret | quote }}
{{- end -}}
