{{- if and .Values.service.enabled .Values.config.metricsPort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyjobkit.fullname" . }}-metrics
  labels: {{- include "pyjobkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "pyjobkit.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end -}}
